<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['title','dueDate','description','group_id','subject_id','return'];

    public function save(array $options = [])
    {
        if(!isset($this->user_id)){
            $this->user_id = auth()->user()->id;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }
}
